name: Private iCampus Data Fetch

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Download ChromeDriver and Chrome
        uses: nanasess/setup-chromedriver@v2
      - name: Start headless chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
        # Chrome/Chromium in headless for Selenium

      - name: Run scraper
        env:
          ICAMPUS_USER: ${{ secrets.ICAMPUS_USER }}
          ICAMPUS_PASS: ${{ secrets.ICAMPUS_PASS }}
        run: |
          python icampus_scraper.py --username "$ICAMPUS_USER" --password "$ICAMPUS_PASS"

      - name: Upload mydata.json as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: mydata
          path: mydata.json
